name: "Build to Branch"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
      - name: Install PNPM
        run: npm i -g pnpm
      - name: PNPM Instll
        run: pnpm install
      - name: Build the extension
        run: pnpm build
      - name: Deploy to a branch
        run: |
          TARGET_BRANCH="build-branch"
          ls build
          git branch
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git ls-remote --exit-code origin $TARGET_BRANCH; then
            git fetch origin $TARGET_BRANCH
            git switch $TARGET_BRANCH
          else
            git checkout -b $TARGET_BRANCH
          fi
          git branch
          find . -mindepth 1 -maxdepth 1 -not -name "build" -not -name ".git" -exec rm -rf {} +
          if [ -d "build" ]; then
            cp -R build/* .
            rm -rf build
          fi
          git init
          git add .
          git commit -m "Build output for branch $GITHUB_SHA"
          git push --force origin $TARGET_BRANCH